Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (100,'\n[ \t]*(Diagnosis:|DIAGNOSIS|Clinical[ ]+Diagnosis:|CLINICAL[ ]+DIAGNOSIS[:]*|Diagnosis[ \t]*\n)','CLINICAL_DIAGNOSIS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (101,'[\n]{2,}[ ]*(Case:|CASE)','CASE_IDENTIFICATION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (102,'[\n]{2,}[ ]*(Complete Blood Count|Complete Blood Count \(CBC\))','COMPLETE_BLOOD_COUNT',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (103,'\n[ \t]*(Clinical[ \t]+[Ii]nformation[:]*|CLINICAL[ \t]+INFORMATION[:]*)[ \t]*\n','CLINICAL_INFORMATION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (104,'[\n]{2,}[ ]*(Laboratory [.]+ Data[ ]*[\n]|Laboratory \( CBC/Diff Counts\) Data)','LAB_DATA',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (105,'\n[ \t]*(Bone [Mm]arrow [Dd]ifferential[ \t]*\n|BONE MARROW Differential|BLOOD[\s\n]{1,5}MARROW[\s\n]{1,5}MARROW NORMAL)','BONE_MARROW_DIFFERENTIAL',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (106,'[\n]{2,}[ ]*(Peripheral Blood Differential|PB Differential)','PERIPHERAL_BLOOD_DIFFERENTIAL',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (107,'[\n]{2,}[ ]*(Peripheral Smear|Peripheral Smear:|Peripheral Blood Smear)','PERIPHERAL_SMEAR',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (108,'([\n]{1,}[ ]*(Bone Marrow Aspirate[\/ ]*Touch Imprint|Bone Marrow Aspirate))|(Bone Marrow Aspirate:|Bone Marrow Aspirate and Touch Imprint:|Bone Marrow Aspirate[\/ ]*(Touch)*[ ]*Imprint)','BONE_MARROW_ASPIRATE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (109,'([\n]{2,}[ ]*Bone Marrow Biopsy)|Bone Marrow Biopsy:','BONE_MARROW_BIOPSY',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (200,'([\n]{1,}[ \t]*(COMMENT|Comment[ \t]*([\n]+|[ ]{4,})[\t ]*))|([\s\t]+|[.])(Comment:|COMMENT:)','COMMENT',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (201,'[\n]{2,}[ ]*(Gross Description|Gross Description:|GROSS DESCRIPTION)','GROSS_DESCRIPTION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (202,'[\n]{2,}[ ]*(Microscopic Description|Microscopic Description:|MICROSCOPIC DESCRIPTION)','MICROSCOPIC_DESCRIPTION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (303,'\n[ \t]*(Electron Microscopy[:]*|ELECTRON MICROSCOPY[:]*)[\t ]*\n','ELECTRON_MICROSCOPY',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (300,'([\n]{2,}[ ]*Iron[\/ ]+Special Stains)|Iron Stains:|Iron Stain:','IRON_STRAINS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (301,'([\n\t]{2,}[ ]*[A-Z]+[.\t A-Za-z]*[A-Z]+[. \tA-Za-z]*[,]* (M[.]*D[.]*|Ph[.]*D[.]*|M[.]*D[., ]*Ph[.]*D[.]*)[\s\t]*\n)|\n[ \t]{3,}Dr[.]','MD_NAME',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (304,'\n[ \t]*(Immunofluores[c]*ence[:]*[ \t\n]{1,}|IMMUNOFLUORES[C]*ENCE)','IMMUNOFLUORESENCE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (110,'[\n]{1,}[ \t]*(Pathologic Diagnosis[:]{0,1}|PATHOLOGIC DIAGNOSIS[:]{0,1})[\n \t]{1,}','PATHOLOGIC_DIAGNOSIS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (111,'[\n\t ]{2,}BLOOD[\n\t]+MARROW[\n\t]+NORMAL[%]','BONE_MARROW_PTH_TABLE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (112,'[\n\t]{2,}[ \t]*(BM Addendum Report[:]*|BONE MARROW ADDENDUM[:]*|Bone Marrow Addendum[:]*|Bone Marrow Addendum Report[:]*)','BM_ADDENDUM_REPORT',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (113,'[\n]{2,}[ \t]*ASPIRATE\n','BONE_MARROW_PTH_ASPIRATE_TABLE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (203,'\n[ \t]*Pathologist Comment[s]{0,1}[:\s\n]{1,}','PATHOLOGIST_COMMENTS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (400,'[\n]{1,}[ \t]*(Result:|RESULT)[\n\t ]{1,}','KARYOTYPE_RESULT',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (401,'[\n]{1,}[ \t]*(Interpretation:|INTERPRETATION)[\n\t ]{1,}','KARYOTYPE_INTERPRETATION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (402,'\n[ \t]*(Chromosome Analysis[:]*|CHROMOSOME ANALYSIS[:]*)[\t ]*\n','CHROMOSOME_ANALYSIS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (403,'\n[ \t]*FISH[ ]+(Analysis|ANALYSIS)[:]*[\t ]*\n','FISH_ANALYSIS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (404,'[\n]{2,}[ \t]*(CYTOGENETICS[ \t]+REPORT)[\t ]*\n','CYTOGENETICS_REPORT',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (405,'\n[\t ]*\n[ \t]*(Results[:]*|RESULTS[:]*)[\t ]*\n[\t ]*\n','RESULTS_FOR_CYTOGENETICS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (500,'([\n]{1,}[ \t]*(IMPRESSION[S]*|Impression[s]*[ \t]*([\n]+|[ ]{4,})[\t ]*))|([\s\t]+|[.])(Impression[s]*:|IMPRESSION[S]*:)','IMPRESSION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (607,'\n[ \t]*(Assessment of T-Scores:|ASSESSMENT OF T-SCORES[:]*)[\t ]*','ASSESSMENT OF T-SCORES',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (3,'(PROCEDURES:|Procedures:|Procedure:|PROCEDURE:|PROCEDURE LIST:|Procedure List:|Procedure History:|PROCEDURE HISTORY:|PAST SURGICAL HISTORY:|SURGICAL HISTORY:|Surgical History:|Past Surgical History)','PROCEDURES',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (4,'[\r\n]+A(LLERGIES|LLERGIES AND INTOLERANCES:|llergies:|lergies:)','ALLERGIES',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (5,'[\r\n]+(CHRONIC|STABLE|Chronic|Stable) (MEDICAL )*P(ROBLEM|roblem):','STABLE_PROBLEMS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (1,'(PROBLEMS:|Problems:|Problem:|PROBLEM:|ACTIVE MEDICAL PROBLEMS:|Condition:|Conditions:|PROBLEM LIST:|Problem List:|Medical History:|MEDICAL HISTORY)','PROBLEMS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (2,'((C(urrent|URRENT))*[ ]*M(edication|EDICATION)([Ss])*:|[\r\n]+D(rug|RUG)([Ss])*:|D(RUG|rug) (list|LIST):|Drug History:|DRUG HISTORY|MEDICATION LIST:|Medication List:|Medication History:|MEDICATION HISTORY|CURRENT MEDICATIONS|Current Medications)','MEDICATIONS',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (6,'[\r\n]+F(AMILY|amily) H(ISTORY|istory):','FAMILY_HISTORY',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (7,'[\r\n]+H(EALTH|ealth) M(AINTENANCE|aintenance):','HEALTH_MAINTENANCE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (8,'([Ee]lectronically [Ss]igned|P(atient|ATIENT) T(racking|RACKING) L(ist|IST)|[pP]atient [Ss]ummary [Ll]ist|PATIENT SUMMARY LIST|[~*]*Last updated by|[\r\n]*[|]*[~]*Dictated by)[\s\S]+','PTL_FOOTER',1);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (600,'\n[ \t]*([Rr]eason [Ff]or [Ee]xam[:]*|REASON FOR EXAM[:]*)[\t ]*\n','REASON FOR EXAM',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (601,'\n[ \t]*([Rr]eport [Oo]f [Ee]xam[:]*|REPORT OF EXAM[:]*)[\t ]*\n','REPORT OF EXAM',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (602,'\n[ \t]*(Indication:|INDICATION[:]*)[\t ]*','INDICATION',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (604,'\n[ \t]*(Technique:|TECHNIQUE[:]*)[\t ]*','TECHNIQUE',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (605,'\n[ \t]*(Comparison:|COMPARISON[:]*)[\t ]*','COMPARISON',0);
Insert into REF_SEGMENT_REGEX (SEGMENT_REGEX_ID,REGEX,SEGMENT_ID,LIMIT_TO_REGEX) values (606,'\n[ \t]*(Impression:|IMPRESSION[:]*)[\t ]*','IMPRESSION',0);

-- commit;
